### PR TITLE
Gtranslate+web speech api

### PR DESCRIPTION
**Pull request by JHrique**

### CODE REVIEW

**Comment by bateman** [comment]
Joao,
how are you combining skype4java with the existing code base?

**Comment by JHrique** [comment]
I downloaded the google-api-translate-java-0.97.jar, so I have acess the
the classes TranslatorV2, this class provides me methods to set my google
key and the link I want to surf on the web.

Then I used the Skype class u sent and modified it to, before send a
message to a friend, I call the google translator, passing the text,
translating and then the new text is send by chat.

I can try with you right now.

2014-09-08 11:24 GMT-03:00 Fabio Calefato notifications@github.com:

**Comment by bateman** [comment]
does it also support speech recogntion or only translation ?

---

Dr. Fabio Calefato, PhD
University of Bari - Dip. di Informatica
Via E. Orabona, 4 - 70125 Bari - ITALY

home: http://cdg.di.uniba.it/calefato
blog:   http://collab.di.uniba.it/blog
office: +39 080 544 3261
fax:    +39 080 544 2031

**Comment by JHrique** [comment]
For now, just translation.

I have to study the links you sent me, because I never used JavaFX, or Chromium
Embedded Framework, then I could add recognition.

2014-09-08 11:37 GMT-03:00 Fabio Calefato notifications@github.com:

> does it also support speech recogntion or only translation ?
> 
> ---
> 
> Dr. Fabio Calefato, PhD
> University of Bari - Dip. di Informatica
> Via E. Orabona, 4 - 70125 Bari - ITALY
> 
> home: http://cdg.di.uniba.it/calefato
> blog: http://collab.di.uniba.it/blog
> office: +39 080 544 3261
> fax: +39 080 544 2031
>

**Comment by bateman** [comment]
so try to add recognition first, then we test it together

---

Dr. Fabio Calefato, PhD
University of Bari - Dip. di Informatica
Via E. Orabona, 4 - 70125 Bari - ITALY

home: http://cdg.di.uniba.it/calefato
blog:   http://collab.di.uniba.it/blog
office: +39 080 544 3261
fax:    +39 080 544 2031

**Comment by JHrique** [comment]
> > so try to add recognition first, then we test it together
> > Ok, I'll do that.

Just to be clear, if I missed to explain something:

1- We have a first prototype having the recognition, translation and
synthesis (only EN-IT, IT-PT), the one you have changed a bit and tested,
and its lacking the synthesis in Portuguese (Its not a chat, we still have
to do some manual operations...);

2- We now have this Skype4Java, which is very nice, as you said, we have a
very good platform under the solution, with quality. The chat 1-1 is done,
with translation, now we'll add speech recognition. This is next step I'll
focus.

Thanks for indicating the Skype4Java, its works really well

2014-09-08 11:42 GMT-03:00 Fabio Calefato notifications@github.com:

> so try to add recognition first, then we test it together
> 
> ---
> 
> Dr. Fabio Calefato, PhD
> University of Bari - Dip. di Informatica
> Via E. Orabona, 4 - 70125 Bari - ITALY
> 
> home: http://cdg.di.uniba.it/calefato
> blog: http://collab.di.uniba.it/blog
> office: +39 080 544 3261
> fax: +39 080 544 2031
>

**Comment by bateman** [comment]
@JHrique, don't send pull request to merge into the master. We will do that when we have a working, final prototype. For now, stick to the technology-specific branch you're already working on. Thanks!

**Comment by JHrique** [comment]
Ok, that was a mistake, sorry.

2014-09-08 13:19 GMT-03:00 Fabio Calefato notifications@github.com:

**Comment by bateman** [comment]
no worries!

---

Dr. Fabio Calefato, PhD
University of Bari - Dip. di Informatica
Via E. Orabona, 4 - 70125 Bari - ITALY

home: http://cdg.di.uniba.it/calefato
blog:   http://collab.di.uniba.it/blog
office: +39 080 544 3261
fax:    +39 080 544 2031

**Comment by bateman** [comment]
@JHrique Joao, instead of mixing the web app with the Skype4Java solution, please commit the content of the zip file you committed yesterday (GoogleTranslatorAPI.zip) to the proper branch: https://github.com/collab-uniba/speech-translation-tools/tree/skype4java
Thanks!

**Comment by JHrique** [comment]
Done. Now everything is into the correct branches.

João Henrique

2014-09-09 5:51 GMT-03:00 Fabio Calefato notifications@github.com:

**Pull request merged**
